### PR TITLE
Default webhdfs.js header for PUT/POST to octet-stream

### PR DESCRIPTION
**Pull request by bernadinm**
This happens for servers running CDH when you check the headers but breaks for other instances in hadoop like MapR, Bluedata or IBM InfoSphere BigInsights. Somehow it defaults to application/json and will not perform any uploads. This fix will ensure consistency with other WebHDFS and HttpFS servers.

Example of it defaulted to octet-stream without specifying it on CDH. This does not do the same on other servers.
http://foo.bar.com:50070/webhdfs/v1/hdi/ff7b469a-6174-4f13-a397-8d93e67f1e67.txt?op=create&user.name=hdfs&overwrite=true&permissions=0777
{ method: 'PUT',
  url: 'http://foo.bar.com:50070/webhdfs/v1/hdi/ff7b469a-6174-4f13-a397-8d93e67f1e67.txt?op=create&user.name=hdfs&overwrite=true&permissions=0777' }
{ domain: null,
  _events: 
   { error: [ [Object], [Object] ],
     complete: { [Function] __original_callback__: [Function] },
     pipe: [ [Object], [Object] ],
     data: { [Function] __original_callback__: [Function: onError] } },
  _maxListeners: 10,
  readable: true,
  writable: true,
  method: 'PUT',
  headers: 
   { '0': { name: 'content-type', value: 'application/octet-stream' },
     host: 'foo.bar.com:50070',
     'content-type': 'application/octet-stream' },
  callback: [Function],
  explicitMethod: true,
  canTunnel: 
   { httpOverHttp: [Function: httpOverHttp],
     httpsOverHttp: [Function: httpsOverHttp],
     httpOverHttps: [Function: httpOverHttps],
     httpsOverHttps: [Function: httpsOverHttps],
     debug: [Function] },
  localAddress: undefined,
  pool: {},
  dests: [],
  __isRequestRequest: true,
  _callback: [Function],
  uri: 
   { protocol: 'http:',
     slashes: true,
     auth: null,
     host: 'foo.bar.com:50070',
     port: '50070',
     hostname: 'foo.bar.com',
     hash: null,
     search: '?op=create&user.name=hdfs&overwrite=true&permissions=0777',
     query: 'op=create&user.name=hdfs&overwrite=true&permissions=0777',
     pathname: '/webhdfs/v1/hdi/ff7b469a-6174-4f13-a397-8d93e67f1e67.txt',
     path: '/webhdfs/v1/hdi/ff7b469a-6174-4f13-a397-8d93e67f1e67.txt?op=create&user.name=hdfs&overwrite=true&permissions=0777',
     href: 'http://foo.bar.com:50070/webhdfs/v1/hdi/ff7b469a-6174-4f13-a397-8d93e67f1e67.txt?op=create&user.name=hdfs&overwrite=true&permissions=0777' },
  _redirectsFollowed: 0,
  maxRedirects: 10,
  followRedirect: true,
  followAllRedirects: false,
  redirects: [],
  setHost: true,
  originalCookieHeader: undefined,
  _disableCookies: true,
  _jar: undefined,
  port: '50070',
  host: 'foo.bar.com',
  clientErrorHandler: [Function],
  _parserErrorHandler: [Function],
  path: '/webhdfs/v1/hdi/ff7b469a-6174-4f13-a397-8d93e67f1e67.txt?op=create&user.name=hdfs&overwrite=true&permissions=0777',
  httpModule: 
   { parsers: 
      { name: 'parsers',
        constructor: [Function],
        max: 1000,
        list: [Object] },
     STATUS_CODES: 
      { '100': 'Continue',
        '101': 'Switching Protocols',
        '102': 'Processing',
        '200': 'OK',
        '201': 'Created',
        '202': 'Accepted',
        '203': 'Non-Authoritative Information',
        '204': 'No Content',
        '205': 'Reset Content',
        '206': 'Partial Content',
        '207': 'Multi-Status',
        '300': 'Multiple Choices',
        '301': 'Moved Permanently',
        '302': 'Moved Temporarily',
        '303': 'See Other',
        '304': 'Not Modified',
        '305': 'Use Proxy',
        '307': 'Temporary Redirect',
        '400': 'Bad Request',
        '401': 'Unauthorized',
        '402': 'Payment Required',
        '403': 'Forbidden',
        '404': 'Not Found',
        '405': 'Method Not Allowed',
        '406': 'Not Acceptable',
        '407': 'Proxy Authentication Required',
        '408': 'Request Time-out',
        '409': 'Conflict',
        '410': 'Gone',
        '411': 'Length Required',
        '412': 'Precondition Failed',
        '413': 'Request Entity Too Large',
        '414': 'Request-URI Too Large',
        '415': 'Unsupported Media Type',
        '416': 'Requested Range Not Satisfiable',
        '417': 'Expectation Failed',
        '418': 'I\'m a teapot',
        '422': 'Unprocessable Entity',
        '423': 'Locked',
        '424': 'Failed Dependency',
        '425': 'Unordered Collection',
        '426': 'Upgrade Required',
        '428': 'Precondition Required',
        '429': 'Too Many Requests',
        '431': 'Request Header Fields Too Large',
        '500': 'Internal Server Error',
        '501': 'Not Implemented',
        '502': 'Bad Gateway',
        '503': 'Service Unavailable',
        '504': 'Gateway Time-out',
        '505': 'HTTP Version Not Supported',
        '506': 'Variant Also Negotiates',
        '507': 'Insufficient Storage',
        '509': 'Bandwidth Limit Exceeded',
        '510': 'Not Extended',
        '511': 'Network Authentication Required' },
     IncomingMessage: { [Function: IncomingMessage] super_: [Object] },
     OutgoingMessage: { [Function: OutgoingMessage] super_: [Object] },
     ServerResponse: { [Function: ServerResponse] super_: [Object] },
     Agent: { [Function: Agent] super_: [Object], defaultMaxSockets: 5 },
     globalAgent: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        options: {},
        requests: {},
        sockets: [Object],
        maxSockets: 5,
        createConnection: [Function] },
     ClientRequest: { [Function: ClientRequest] super_: [Object] },
     request: [Function],
     get: [Function],
     Server: { [Function: Server] super_: [Object] },
     createServer: [Function],
     _connectionListener: [Function: connectionListener],
     Client: [Function: deprecated],
     createClient: [Function: deprecated] },
  agentClass: 
   { [Function: Agent]
     super_: { [Function: EventEmitter] listenerCount: [Function] },
     defaultMaxSockets: 5 },
  agent: 
   { domain: null,
     _events: { free: [Function] },
     _maxListeners: 10,
     options: {},
     requests: {},
     sockets: { 'foo.bar.com:50070': [Object] },
     maxSockets: 5,
     createConnection: [Function] } }
pipe works? &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
does it get to stream.pipe
{ domain: null,
  _events: 
   { error: { [Function] __original_callback__: [Function] },
     complete: { [Function] __original_callback__: [Function] },
     pipe: { [Function] __original_callback__: [Function] } },
  _maxListeners: 10,
  readable: true,
  writable: true,
  method: 'PUT',
  callback: [Function],
  explicitMethod: true,
  canTunnel: 
   { httpOverHttp: [Function: httpOverHttp],
     httpsOverHttp: [Function: httpsOverHttp],
     httpOverHttps: [Function: httpOverHttps],
     httpsOverHttps: [Function: httpsOverHttps],
     debug: [Function] },
  localAddress: undefined,
  pool: {},
  dests: [],
  __isRequestRequest: true,
  _callback: [Function],
  uri: 
   { protocol: 'http:',
     slashes: true,
     auth: null,
     host: 'fee.bar.com:50075',
     port: '50075',
     hostname: 'fee.bar.com',
     hash: null,
     search: '?op=CREATE&user.name=hdfs&namenoderpcaddress=foo.bar.com:8020&overwrite=true',
     query: 'op=CREATE&user.name=hdfs&namenoderpcaddress=foo.bar.com:8020&overwrite=true',
     pathname: '/webhdfs/v1/hdi/ff7b469a-6174-4f13-a397-8d93e67f1e67.txt',
     path: '/webhdfs/v1/hdi/ff7b469a-6174-4f13-a397-8d93e67f1e67.txt?op=CREATE&user.name=hdfs&namenoderpcaddress=foo.bar.com:8020&overwrite=true',
     href: 'http://fee.bar.com:50075/webhdfs/v1/hdi/ff7b469a-6174-4f13-a397-8d93e67f1e67.txt?op=CREATE&user.name=hdfs&namenoderpcaddress=foo.bar.com:8020&overwrite=true' },
  _redirectsFollowed: 0,
  maxRedirects: 10,
  followRedirect: true,
  followAllRedirects: false,
  redirects: [],
  headers: { host: 'fee.bar.com:50075' },
  setHost: true,
  originalCookieHeader: undefined,
  _disableCookies: true,
  _jar: undefined,
  port: '50075',
  host: 'fee.bar.com',
  clientErrorHandler: [Function],
  _parserErrorHandler: [Function],
  path: '/webhdfs/v1/hdi/ff7b469a-6174-4f13-a397-8d93e67f1e67.txt?op=CREATE&user.name=hdfs&namenoderpcaddress=foo.bar.com:8020&overwrite=true',
  httpModule: 
   { parsers: 
      { name: 'parsers',
        constructor: [Function],
        max: 1000,
        list: [Object] },
     STATUS_CODES: 
      { '100': 'Continue',
        '101': 'Switching Protocols',
        '102': 'Processing',
        '200': 'OK',
        '201': 'Created',
        '202': 'Accepted',
        '203': 'Non-Authoritative Information',
        '204': 'No Content',
        '205': 'Reset Content',
        '206': 'Partial Content',
        '207': 'Multi-Status',
        '300': 'Multiple Choices',
        '301': 'Moved Permanently',
        '302': 'Moved Temporarily',
        '303': 'See Other',
        '304': 'Not Modified',
        '305': 'Use Proxy',
        '307': 'Temporary Redirect',
        '400': 'Bad Request',
        '401': 'Unauthorized',
        '402': 'Payment Required',
        '403': 'Forbidden',
        '404': 'Not Found',
        '405': 'Method Not Allowed',
        '406': 'Not Acceptable',
        '407': 'Proxy Authentication Required',
        '408': 'Request Time-out',
        '409': 'Conflict',
        '410': 'Gone',
        '411': 'Length Required',
        '412': 'Precondition Failed',
        '413': 'Request Entity Too Large',
        '414': 'Request-URI Too Large',
        '415': 'Unsupported Media Type',
        '416': 'Requested Range Not Satisfiable',
        '417': 'Expectation Failed',
        '418': 'I\'m a teapot',
        '422': 'Unprocessable Entity',
        '423': 'Locked',
        '424': 'Failed Dependency',
        '425': 'Unordered Collection',
        '426': 'Upgrade Required',
        '428': 'Precondition Required',
        '429': 'Too Many Requests',
        '431': 'Request Header Fields Too Large',
        '500': 'Internal Server Error',
        '501': 'Not Implemented',
        '502': 'Bad Gateway',
        '503': 'Service Unavailable',
        '504': 'Gateway Time-out',
        '505': 'HTTP Version Not Supported',
        '506': 'Variant Also Negotiates',
        '507': 'Insufficient Storage',
        '509': 'Bandwidth Limit Exceeded',
        '510': 'Not Extended',
        '511': 'Network Authentication Required' },
     IncomingMessage: { [Function: IncomingMessage] super_: [Object] },
     OutgoingMessage: { [Function: OutgoingMessage] super_: [Object] },
     ServerResponse: { [Function: ServerResponse] super_: [Object] },
     Agent: { [Function: Agent] super_: [Object], defaultMaxSockets: 5 },
     globalAgent: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        options: {},
        requests: {},
        sockets: [Object],
        maxSockets: 5,
        createConnection: [Function] },
     ClientRequest: { [Function: ClientRequest] super_: [Object] },
     request: [Function],
     get: [Function],
     Server: { [Function: Server] super_: [Object] },
     createServer: [Function],
     _connectionListener: [Function: connectionListener],
     Client: [Function: deprecated],
     createClient: [Function: deprecated] },
  agentClass: 
   { [Function: Agent]
     super_: { [Function: EventEmitter] listenerCount: [Function] },
     defaultMaxSockets: 5 },
  agent: 
   { domain: null,
     _events: { free: [Function] },
     _maxListeners: 10,
     options: {},
     requests: {},
     sockets: { 'foo.bar.com:50070': [Object] },
     maxSockets: 5,
     createConnection: [Function] } }
did it finish upload? #################################################

Documentation:
https://www-01.ibm.com/support/knowledgecenter/SSPT3X_3.0.0/com.ibm.swg.im.infosphere.biginsights.admin.doc/doc/admin_fileupload_rest_apis.html

### CODE REVIEW

**Comment by bernadinm** [comment]
Just wanted to know if anybody else has taken a look at this fix. 

I figured other people will have this problem and just wanted to share this with everyone.

**Comment by harrisiirak** [comment]
Hi @bernadinm!

Sorry, I missed your PR initially. Doesn't happen with default Hadoop installation tho. Defaulting to octet-stream should be okay, but I need to test it before I can merge it.

BR,
Harri

**Comment by bernadinm** [comment]
Hi @harrisiirak,

No problem. I expect it to work with the default Hadoop installation. It will work with other installations as well. Looking forward to your test.

Thanks again for the reply.

**Comment by harrisiirak** [comment]
Tested it and looks good. Going to merge it. Thanks again!

**Pull request merged**
